version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python -m uvicorn redis-stream-v2:app --reload --host 0.0.0.0 --port 8000
    # command: python -m uvicorn main:app --reload

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
