version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python -m uvicorn main:app --reload --host 127.0.0.1 --port 8000

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
